export const SET_PRINTER_IP_ADDRESS = 'APP/SET_PRINTER_IP_ADDRESS';
export const SYNC_EVERYTHING = 'APP/SYNC_EVERYTHING';
export const REQUEST_RESTAURANT = 'APP/REQUEST_RESTAURANT';
export const REQUEST_USER = 'APP/REQUEST_USER';
export const CREATE_PRINTER = 'APP/CREATE_PRINTER';
export const DELETE_PRINTER = 'APP/CREATE_PRINTER';
export const UPDATE_PRINTER = 'APP/UPDATE_PRINTER';
export const SET_PRINTER_ALERT = 'APP/SET_PRINTER_ALERT';
